# Generated by Django 4.1.6 on 2023-03-05 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('lowerbound', models.PositiveBigIntegerField(unique=True)),
                ('upperbound', models.PositiveBigIntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=20, null=True)),
                ('feedback', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_type', models.CharField(choices=[('Admin', 'admin'), ('User', 'user')], max_length=5)),
                ('user_name', models.CharField(max_length=10, unique=True)),
                ('age', models.PositiveBigIntegerField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('mobile_no', models.CharField(max_length=10, unique=True)),
                ('city', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.person')),
                ('height', models.FloatField()),
                ('weight', models.FloatField()),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female'), ('O', 'others')], max_length=1)),
                ('breakfast', models.CharField(max_length=10)),
                ('lunch', models.CharField(max_length=10)),
                ('dinner', models.CharField(max_length=10)),
            ],
            bases=('app.person',),
        ),
        migrations.CreateModel(
            name='Suggested_Food_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fat', models.FloatField()),
                ('Users', models.ManyToManyField(to='app.user')),
            ],
        ),
        migrations.CreateModel(
            name='Food_Item',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=10)),
                ('calories', models.FloatField()),
                ('proteins', models.FloatField()),
                ('fat', models.FloatField()),
                ('category', models.ForeignKey(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], on_delete=django.db.models.deletion.CASCADE, to='app.category')),
                ('Users', models.ManyToManyField(to='app.user')),
            ],
        ),
    ]
